networks:
  internal-network:
    name: docker-internal

services:
  main-proxy:
    image: onixldlc/nginx-ui:latest
    container_name: nginx-ui
    networks:
      internal-network:
    restart: unless-stopped
    volumes:
      - "./config/nginx:/etc/nginx"
      - "./config/nginx-ui:/etc/nginx-ui"
    environment:
      - TZ=Asia/Bangkok
      - SERVER_NAME=localhost
    ports:
      - 80:80
      - 443:443
      - 9000:9000   # optional